// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Digital.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DigitalLoginAndLogoutFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DigitalLoginLogout.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DigitalLoginAndLogout", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "DigitalLoginAndLogout")))
            {
                Digital.FeatureFiles.DigitalLoginAndLogoutFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void LoginAndLogoutOfDigital()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login and Logout of Digital", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("I have navigated to Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I Login using dcplantest@dcplantest.com/Bolder11", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("I should see account details and Logout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void LoginAndLogoutOfDigitalMultipleTimes(string userName, string password, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login and Logout of Digital multiple times", exampleTags);
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
 testRunner.And("I have navigated to Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.When(string.Format("I Login to Digital using \'{0}\' and \'{1}\' through data from feature file", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("I should see account details and Logout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation1Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation1@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation2Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation2@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation3Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation3@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation4Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation4@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation5Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation5@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation6@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation6@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation6@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation6Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation6@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation7@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation7@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation7@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation7Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation7@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation8Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation8@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation9@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation9@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation9@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation9Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation9@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation10@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation10@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation10@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation10Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation10@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation11@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation11@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation11@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation11Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation11@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation12@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation12@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation12@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation12Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation12@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Login and Logout of Digital multiple times: automation13@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "automation13@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "automation13@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        public virtual void LoginAndLogoutOfDigitalMultipleTimes_Automation13Test_Com()
        {
            this.LoginAndLogoutOfDigitalMultipleTimes("automation13@test.com", "Bolder@11", ((string[])(null)));
#line hidden
        }
        
        public virtual void TestErrorMessagesForExcludedAccounts(string userName, string password, string errorMessage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test Error Messages for excluded accounts", exampleTags);
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.And("I have navigated to Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.When(string.Format("I Login to Digital using \'{0}\' and \'{1}\' through data from feature file", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then(string.Format("I should see this error message \'{0}\' in place of payment options", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.And("I should see account details and Logout", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: autorun2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "autorun2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "autorun2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help.")]
        public virtual void TestErrorMessagesForExcludedAccounts_Autorun2Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("autorun2@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help.", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: autorun8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "autorun8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "autorun8@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help.")]
        public virtual void TestErrorMessagesForExcludedAccounts_Autorun8Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("autorun8@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help.", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: uattest5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "uattest5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "uattest5@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help.")]
        public virtual void TestErrorMessagesForExcludedAccounts_Uattest5Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("uattest5@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help.", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: autorunexc1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "autorunexc1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "autorunexc1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
            "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
            "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk")]
        public virtual void TestErrorMessagesForExcludedAccounts_Autorunexc1Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("autorunexc1@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
                    "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
                    "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: autorunexc2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "autorunexc2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "autorunexc2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
            "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
            "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk")]
        public virtual void TestErrorMessagesForExcludedAccounts_Autorunexc2Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("autorunexc2@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
                    "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
                    "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: autorunexc3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "autorunexc3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "autorunexc3@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
            "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
            "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk")]
        public virtual void TestErrorMessagesForExcludedAccounts_Autorunexc3Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("autorunexc3@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online. Please contact Insolvency t" +
                    "eam. Our opening times are Mon – Fri opening times 9am – 5pm. Direct Telephone N" +
                    "umber : 0333 556 5990 or Email : insolvencyteam@lowellgroup.co.uk", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: excluded2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "excluded2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "excluded2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", @"Your account has been forwarded to a debt collection agency and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be happy to help. Our opening times are Mon – Fri 8.00am -8.00pm and Sat 8am – 2pm")]
        public virtual void TestErrorMessagesForExcludedAccounts_Excluded2Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("excluded2@test.com", "Bolder@11", @"Your account has been forwarded to a debt collection agency and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be happy to help. Our opening times are Mon – Fri 8.00am -8.00pm and Sat 8am – 2pm", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: outsourced1@outsourced1.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "outsourced1@outsourced1.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "outsourced1@outsourced1.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", @"Your account has been forwarded to a debt collection agency : BPO Collections, telephone number 0123456780 and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact your agency.")]
        public virtual void TestErrorMessagesForExcludedAccounts_Outsourced1Outsourced1_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("outsourced1@outsourced1.com", "Bolder@11", @"Your account has been forwarded to a debt collection agency : BPO Collections, telephone number 0123456780 and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact your agency.", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: tester1@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "tester1@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "tester1@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", @"We’re aware there is a query with this account and will contact you when we have a resolution. If you have any questions please contact us. Our opening times are Mon – Fri 8am – 8pm and Sat 8am-2pm. Email us at support@lowellgroup.co.uk or telephone us on 0333 556 5551")]
        public virtual void TestErrorMessagesForExcludedAccounts_Tester1Statii_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("tester1@statii.com", "Bolder@11", @"We’re aware there is a query with this account and will contact you when we have a resolution. If you have any questions please contact us. Our opening times are Mon – Fri 8am – 8pm and Sat 8am-2pm. Email us at support@lowellgroup.co.uk or telephone us on 0333 556 5551", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: tester2@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "tester2@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "tester2@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", @"We’re aware there is a query with this account and will contact you when we have a resolution. If you have any questions please contact us. Our opening times are Mon – Fri 8am – 8pm and Sat 8am-2pm. Email us at support@lowellgroup.co.uk or telephone us on 0333 556 5551")]
        public virtual void TestErrorMessagesForExcludedAccounts_Tester2Statii_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("tester2@statii.com", "Bolder@11", @"We’re aware there is a query with this account and will contact you when we have a resolution. If you have any questions please contact us. Our opening times are Mon – Fri 8am – 8pm and Sat 8am-2pm. Email us at support@lowellgroup.co.uk or telephone us on 0333 556 5551", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: tester3@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "tester3@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "tester3@statii.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", @"Your account has been forwarded to a debt collection agency and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be happy to help. Our opening times are Mon – Fri 8.00am -8.00pm and Sat 8am – 2pm")]
        public virtual void TestErrorMessagesForExcludedAccounts_Tester3Statii_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("tester3@statii.com", "Bolder@11", @"Your account has been forwarded to a debt collection agency and therefore you cannot make payment or set up plans on line. You can view account details if you are logged in. If you have any queries, please contact us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be happy to help. Our opening times are Mon – Fri 8.00am -8.00pm and Sat 8am – 2pm", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: repcode2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "repcode2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "repcode2@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm")]
        public virtual void TestErrorMessagesForExcludedAccounts_Repcode2Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("repcode2@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: exclude1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "exclude1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "exclude1@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm")]
        public virtual void TestErrorMessagesForExcludedAccounts_Exclude1Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("exclude1@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Test Error Messages for excluded accounts: tokentest4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DigitalLoginAndLogout")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "tokentest4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:userName", "tokentest4@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:password", "Bolder@11")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:error message", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
            "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
            "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm")]
        public virtual void TestErrorMessagesForExcludedAccounts_Tokentest4Test_Com()
        {
            this.TestErrorMessagesForExcludedAccounts("tokentest4@test.com", "Bolder@11", "We’re sorry you’re unable to pay this account online at the moment. Please contac" +
                    "t us at support@lowellgroup.co.uk or phone us on 0333 556 5551 where we will be " +
                    "happy to help. Our opening times are Mon - Fri 8am - 8pm and Sat 8am - 2pm", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
