// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Digital.FeatureFiles.LoggedOutFeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class LO_DirectDebitPaymentFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LO_DirectDebitPLan.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LO_DirectDebitPayment", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "LO_DirectDebitPayment")))
            {
                Digital.FeatureFiles.LoggedOutFeatureFiles.LO_DirectDebitPaymentFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies(string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string accountNo, string sortCode, string emailAddres, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Set up DD plan with various frequencies", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, accountNo, sortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("I note the value of the Start Date and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.Then(string.Format("the Logged Off Direct Debit Plan Step2 -Review screen displays the values entered" +
                        " \'{0}\', \'{1}\', \'{2}\',\'<AcccountHolder>\',\'{3}\', \'{4}\', \'<EmailAddress>\'", refNo, paymentAmount, frequency, accountNo, sortCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 16
 testRunner.And("the Logged Off Direct Debit Plan Step2 -Review screen displays the other values e" +
                    "ntered: Start Date, Repayment Method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("I click on the Continue button in the Logged Off Direct Debit Plan Step2 -Review " +
                    "screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then(string.Format("the Logged Off Direct Debit Plan Confirmation screen displays the values entered " +
                        "\'{0}\', \'{1}\', \'{2}\',\'{3}\', \'{4}\'", refNo, paymentAmount, frequency, accountNo, sortCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.And("the Logged Off Direct Debit Plan Confirmation screen displays the other values en" +
                    "tered: Start Date, Repayment Method, Account Holder and Email Address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Set up DD plan with various frequencies: Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100022771")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "20/01/1986")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "SW8 1EP")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "14457846")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        public virtual void LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies_Weekly()
        {
            this.LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies("Weekly", "100022771", "20/01/1986", "SW8 1EP", "1.00", "A Test", "14457846", "308088", "autoTestLO@test.com", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Set up DD plan with various frequencies: Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Monthly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100023068")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/02/1989")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "G1 1QD")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "2.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "14457846")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        public virtual void LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies_Monthly()
        {
            this.LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies("Monthly", "100023068", "13/02/1989", "G1 1QD", "2.00", "A Test", "14457846", "308088", "autoTestLO@test.com", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Set up DD plan with various frequencies: Fortnightly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Fortnightly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Fortnightly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100023837")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "03/06/1968")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "HU1 3RT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "3.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "14457846")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        public virtual void LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies_Fortnightly()
        {
            this.LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies("Fortnightly", "100023837", "03/06/1968", "HU1 3RT", "3.00", "A Test", "14457846", "308088", "autoTestLO@test.com", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Set up DD plan with various frequencies: Four Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Four Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Four Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100024363")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "09/02/1969")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B36 0UB")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "4.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "14457846")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        public virtual void LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies_FourWeekly()
        {
            this.LoggedOutDDPlan_SetUpDDPlanWithVariousFrequencies("Four Weekly", "100024363", "09/02/1969", "B36 0UB", "4.00", "A Test", "14457846", "308088", "autoTestLO@test.com", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_ValidateBankAccountForNon_ExistentAccountNumber(string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string nonExistentAccountNo, string sortCode, string emailAddres, string nonExistentAccountNumberErrorMessage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Validate Bank Account for non-existent account number", exampleTags);
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, nonExistentAccountNo, sortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("I click on the Continue button in the Logged Off Direct Debit Plan Step1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.Then(string.Format("the non-existent account number error message:  \'{0}\' is displayed in the Logged " +
                        "Off Direct Debit Plan Step1 screen", nonExistentAccountNumberErrorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for non-existent account number: Weekly" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NonExistentAccountNo", "00000000")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:NonExistentAccountNumberErrorMessage", "Please enter a valid account number – if you believe this is valid then contact u" +
            "s so we can help.")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForNon_ExistentAccountNumber_Weekly()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForNon_ExistentAccountNumber("Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "00000000", "308088", "autoTestLO@test.com", "Please enter a valid account number – if you believe this is valid then contact u" +
                    "s so we can help.", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_ValidateBankAccountForModulusCheck(string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string modulusAccountNo, string modulusSortCode, string emailAddres, string modulusErrorMessage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Validate Bank Account for Modulus check", exampleTags);
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 46
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, modulusAccountNo, modulusSortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("I click on the Continue button in the Logged Off Direct Debit Plan Step1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.Then(string.Format("the modulus error message:  \'{0}\' is displayed in the Logged Off Direct Debit Pla" +
                        "n Step1 screen", modulusErrorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 52
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for Modulus check: Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ModulusAccountNo", "12563958")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ModulusSortCode", "201188")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:ModulusErrorMessage", "Please check your bank account and sort code are correct - if you believe they ar" +
            "e correct then contact us so we can help.")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForModulusCheck_Weekly()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForModulusCheck("Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "12563958", "201188", "autoTestLO@test.com", "Please check your bank account and sort code are correct - if you believe they ar" +
                    "e correct then contact us so we can help.", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode(string reason, string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string accountNo, string invalidSortCode, string emailAddres, string sortCodeErrorMessage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Validate Bank Account for invalid sort code", exampleTags);
#line 57
this.ScenarioSetup(scenarioInfo);
#line 58
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 59
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 60
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, accountNo, invalidSortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I click on the Continue button in the Logged Off Direct Debit Plan Step1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.Then(string.Format("the sort code error message:  \'{0}\' is displayed in the Logged Off Direct Debit P" +
                        "lan Step1 screen", sortCodeErrorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid sort code: SortCodeTooShort" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "SortCodeTooShort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "SortCodeTooShort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "12563958")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidSortCode", "12345")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCodeErrorMessage", "Please enter a valid sort code")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode_SortCodeTooShort()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode("SortCodeTooShort", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "12563958", "12345", "autoTestLO@test.com", "Please enter a valid sort code", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid sort code: SortCodeText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "SortCodeText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "SortCodeText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "12563958")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidSortCode", "123a45")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCodeErrorMessage", "Please enter a valid sort code")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode_SortCodeText()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode("SortCodeText", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "12563958", "123a45", "autoTestLO@test.com", "Please enter a valid sort code", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid sort code: SortCodeSpecialC" +
            "har")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "SortCodeSpecialChar")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "SortCodeSpecialChar")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "12563958")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidSortCode", "123?45")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCodeErrorMessage", "Please enter a valid sort code")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode_SortCodeSpecialChar()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidSortCode("SortCodeSpecialChar", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "12563958", "123?45", "autoTestLO@test.com", "Please enter a valid sort code", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber(string reason, string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string invalidAccountNo, string sortCode, string emailAddres, string accountNumberErrorMessage, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Validate Bank Account for invalid account number", exampleTags);
#line 73
this.ScenarioSetup(scenarioInfo);
#line 74
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 75
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, invalidAccountNo, sortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.And("I click on the Continue button in the Logged Off Direct Debit Plan Step1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.Then(string.Format("the account number error message:  \'{0}\' is displayed in the Logged Off Direct De" +
                        "bit Plan Step1 screen", accountNumberErrorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid account number: AccountNumb" +
            "erTooShort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AccountNumberTooShort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "AccountNumberTooShort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidAccountNo", "1234567")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumberErrorMessage", "Please enter a valid account number. If your account number has fewer than 8 digi" +
            "ts please add zeroes in front of the account number")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber_AccountNumberTooShort()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber("AccountNumberTooShort", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "1234567", "308088", "autoTestLO@test.com", "Please enter a valid account number. If your account number has fewer than 8 digi" +
                    "ts please add zeroes in front of the account number", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid account number: AccountNumb" +
            "erText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AccountNumberText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "AccountNumberText")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidAccountNo", "1234567A")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumberErrorMessage", "The field AccountNumber must be a number.")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber_AccountNumberText()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber("AccountNumberText", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "1234567A", "308088", "autoTestLO@test.com", "The field AccountNumber must be a number.", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Validate Bank Account for invalid account number: AccountNumb" +
            "erSpecialChar")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "AccountNumberSpecialChar")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Reason", "AccountNumberSpecialChar")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:InvalidAccountNo", "1234567?")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNumberErrorMessage", "The field AccountNumber must be a number.")]
        public virtual void LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber_AccountNumberSpecialChar()
        {
            this.LoggedOutDDPlan_ValidateBankAccountForInvalidAccountNumber("AccountNumberSpecialChar", "Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "1234567?", "308088", "autoTestLO@test.com", "The field AccountNumber must be a number.", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_LoggedOutUsersCannotSetUpDiscountedDD(string accountType, string refNo, string dOB, string postcode, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Logged out users cannot set up discounted DD", exampleTags);
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.Then("the Discounted DD Amount buttons are NOT displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Logged out users cannot set up discounted DD: Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountType", "Single")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100022185")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "01/07/1967")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "NE34 8HX")]
        public virtual void LoggedOutDDPlan_LoggedOutUsersCannotSetUpDiscountedDD_Single()
        {
            this.LoggedOutDDPlan_LoggedOutUsersCannotSetUpDiscountedDD("Single", "100022185", "01/07/1967", "NE34 8HX", ((string[])(null)));
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Logged out users cannot set up discounted DD: Linked")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Linked")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountType", "Linked")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100053107")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "04/04/1957")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "SP11 0LJ")]
        public virtual void LoggedOutDDPlan_LoggedOutUsersCannotSetUpDiscountedDD_Linked()
        {
            this.LoggedOutDDPlan_LoggedOutUsersCannotSetUpDiscountedDD("Linked", "100053107", "04/04/1957", "SP11 0LJ", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_VerifyBackButtonWorksInReviewPage(string frequency, string refNo, string dOB, string postcode, string paymentAmount, string accountHolder, string accountNo, string sortCode, string emailAddres, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Verify back button works in Review page", exampleTags);
#line 102
this.ScenarioSetup(scenarioInfo);
#line 103
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 104
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.And(string.Format("I complete the Logged Off Direct Debit Plan Step1 screen using \'{0}\',  \'{1}\', \'{2" +
                        "}\', \'{3}\', \'{4}\' and \'{5}\'  through data from feature file", paymentAmount, frequency, accountHolder, accountNo, sortCode, emailAddres), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("I note the value of the Start Date and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.Then(string.Format("the Logged Off Direct Debit Plan Step2 -Review screen displays the values entered" +
                        " \'{0}\', \'{1}\', \'{2}\',\'<AcccountHolder>\',\'{3}\', \'{4}\', \'<EmailAddress>\'", refNo, paymentAmount, frequency, accountNo, sortCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 111
 testRunner.And("I click on the Back button in the the Direct Debit Plan Step2 -Review screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.Then("the Logged Off Direct Debit Plan Step1 screen is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 113
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Verify back button works in Review page: Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Frequency", "Weekly")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1.00")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountHolder", "A Test")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:AccountNo", "14457846")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:SortCode", "308088")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:EmailAddres", "autoTestLO@test.com")]
        public virtual void LoggedOutDDPlan_VerifyBackButtonWorksInReviewPage_Weekly()
        {
            this.LoggedOutDDPlan_VerifyBackButtonWorksInReviewPage("Weekly", "100025949", "13/01/1981", "B60 2BT", "1.00", "A Test", "14457846", "308088", "autoTestLO@test.com", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_CheckDDGuaranteeAndTermsAndConditonsLinksWork(string refNo, string dOB, string postcode, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Check DD Guarantee and Terms and Conditons links work", exampleTags);
#line 119
this.ScenarioSetup(scenarioInfo);
#line 120
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 121
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 122
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("I click on the DD Guarantee link in the logged Off Direct Debit Plan Step1 screen" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.Then("the DD Guarantee PDF is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
 testRunner.And("I click on the Terms and Conditions link in the logged Off Direct Debit Plan Step" +
                    "1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 128
 testRunner.Then("the user is redirected to the Terms and Conditions page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Check DD Guarantee and Terms and Conditons links work: 100025" +
            "949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100025949")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/01/1981")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "B60 2BT")]
        public virtual void LoggedOutDDPlan_CheckDDGuaranteeAndTermsAndConditonsLinksWork_100025949()
        {
            this.LoggedOutDDPlan_CheckDDGuaranteeAndTermsAndConditonsLinksWork("100025949", "13/01/1981", "B60 2BT", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_NavigateFromOneOffPage_VerifyAmountNotPre_Populated(string refNo, string dOB, string postcode, string paymentAmount, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Navigate from One off page. Verify Amount not pre-populated", exampleTags);
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 136
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 137
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("I select Make a one off payment radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.And(string.Format("I complete the Logged Off One Off payment Step1 screen using \'{0}\' through data f" +
                        "rom feature file", paymentAmount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 141
 testRunner.And("I click on the Back button in the Logged Off One Off payment Step1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
 testRunner.And("I select Setup a Direct Debit radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 143
 testRunner.Then("I verify that the Repayment Amount field is NOT pre-populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Navigate from One off page. Verify Amount not pre-populated: " +
            "100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/04/1954")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "OX14 1QN")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:PaymentAmount", "1")]
        public virtual void LoggedOutDDPlan_NavigateFromOneOffPage_VerifyAmountNotPre_Populated_100020395()
        {
            this.LoggedOutDDPlan_NavigateFromOneOffPage_VerifyAmountNotPre_Populated("100020395", "13/04/1954", "OX14 1QN", "1", ((string[])(null)));
#line hidden
        }
        
        public virtual void LoggedOutDDPlan_NavigateFromPayInFullPage_VerifyAmountNotPre_Populated(string refNo, string dOB, string postcode, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Logged Out DDPlan - Navigate from Pay in Full page. Verify Amount not pre-populat" +
                    "ed", exampleTags);
#line 149
this.ScenarioSetup(scenarioInfo);
#line 150
 testRunner.Given("I have opened Digital in Chrome", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 151
 testRunner.When("I click on the Payment Options bubble icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 152
 testRunner.And("I select Payment Options radio button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 153
 testRunner.And(string.Format("I complete Anonymous Login using \'{0}\', \'{1}\' and \'{2}\' through data from feature" +
                        " file", refNo, dOB, postcode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.And("I select Pay in Full radio button and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.Then("the Logged off Pay in Full Page1 screen is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 156
 testRunner.And("I click on the Back button in the Logged off Pay in Full Page1 screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("I select Setup a Direct Debit radio button again and click on Continue", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.Then("I verify that the Repayment Amount field is NOT pre-populated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 159
 testRunner.And("User is navigated to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Logged Out DDPlan - Navigate from Pay in Full page. Verify Amount not pre-populat" +
            "ed: 100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "LO_DirectDebitPayment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:RefNo", "100020395")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:DOB", "13/04/1954")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:Postcode", "OX14 1QN")]
        public virtual void LoggedOutDDPlan_NavigateFromPayInFullPage_VerifyAmountNotPre_Populated_100020395()
        {
            this.LoggedOutDDPlan_NavigateFromPayInFullPage_VerifyAmountNotPre_Populated("100020395", "13/04/1954", "OX14 1QN", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
